# Generated by Django 5.0.6 on 2024-07-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=255)),
                ('goal_description', models.CharField(max_length=255)),
                ('goal_category', models.CharField(max_length=255)),
                ('target_date', models.DateTimeField(auto_now=True, null=True)),
                ('goal_status', models.CharField(max_length=255)),
            ],
        ),
    ]
