# Generated by Django 5.0.6 on 2024-07-08 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management_app', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='level',
            field=models.CharField(choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5')], default='ONE', max_length=5),
        ),
        migrations.AddField(
            model_name='talent',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='promotion_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TALENT', 'Talent'), ('EMPLOYER', 'Employer'), ('MANAGER', 'Manager')], default='EMPLOYER', max_length=50),
        ),
    ]
